# fly.toml app configuration file generated for demo-pg-green-pine-1994 on 2025-12-20T22:15:52-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-pg-green-pine-1994'
primary_region = 'ord'

[build]
  builder = 'docker'

[processes]
  postgres = '/entrypoint.sh'
  redis = '/usr/bin/redis-server --port 6379 --bind 0.0.0.0 --appendonly yes --dir /data'

[env]
  POSTGRES_DB = 'demo_db'
  POSTGRES_PASSWORD = 'password'
  POSTGRES_USER = 'postgres'

[[mounts]]
  source = 'postgres_data'
  destination = '/var/lib/postgresql/data'
  processes = ['postgres']

[[mounts]]
  source = 'redis_data'
  destination = '/data'
  processes = ['redis']

[http_service]
  internal_port = 5432
  processes = ['postgres']

[[services]]
  protocol = 'tcp'
  internal_port = 5432
  processes = ['postgres']

  [[services.ports]]
    port = 5432

[[services]]
  protocol = 'tcp'
  internal_port = 6379
  processes = ['redis']

  [[services.ports]]
    port = 6379

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
